name: consumir
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
#http: paquete para hacer peticiones http
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/logo-login-black.png
    - assets/logo-login-white.png
    - assets/logo-twbs-blanco.png
    - assets/logo-twbs-negro.png